#!/bin/bash
# Step 05 — Run decoy generation on the HPC cluster.
#
# Do not edit this file. Submit via the command printed by script 04:
#     sbatch --chdir=<repo_root> --array=0-<N>%40 scripts/05_run_decoys.sh
# All paths are relative to --chdir (the repository root).

#SBATCH --job-name=camm-eos3e6s
#SBATCH --time=100:00:00
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=4G
#SBATCH --output=output/05_logs/%x_%a.out
#SBATCH --partition=spot_cpu
#SBATCH --nodelist=irbccn16,irbccn41,irbccn42
#SBATCH --requeue

export SINGULARITYENV_LD_LIBRARY_PATH=$LD_LIBRARY_PATH
export SINGULARITY_BINDPATH="/home/sbnb:/aloy/home,/data/sbnb/data:/aloy/data,/data/sbnb/scratch:/aloy/scratch"
export LD_LIBRARY_PATH=/apps/manual/software/CUDA/11.6.1/lib64:/apps/manual/software/CUDA/11.6.1/targets/x86_64-linux/lib:/apps/manual/software/CUDA/11.6.1/extras/CUPTI/lib64/:/apps/manual/software/CUDA/11.6.1/nvvm/lib64/:$LD_LIBRARY_PATH
export PYTHONDONTWRITEBYTECODE=1

alpha_padded="$(printf "%03d" "$SLURM_ARRAY_TASK_ID")"

envs/camm/bin/ersilia_apptainer run \
  --sif output/04_decoys_sif_image/04_eos3e6s_v1.sif \
  --input output/04_positives_splits/split_${alpha_padded}.csv \
  --output output/05_decoys/eos3e6s_${alpha_padded}.csv \
  --verbose
