"""
Step 20 — Cut the next GitHub release for one or more pathogens' Hub repos.

Deliberately separate from the push itself (scripts 18b/19): a release is the only
thing that triggers retag-release-docker.yml (republishes the model's Docker image) —
upload-model.yml runs on every push to main but never creates a release. It refuses to
cut a release unless the post-push CI of the refresh has succeeded.

Per pathogen (ersilia-os/{eosXXXX}, branch main):
  1. Finds the refresh commit: the newest commit on main whose message has no
     "[skip ci]". Everything after it must be a "[skip ci]" commit by ersilia-bot that
     changes only README.md and/or metadata.yml (the updates CI writes itself, which it
     never tests); any other commit after the refresh refuses the release.
  2. Requires the newest "Test and upload model" run to be on that commit and to have
     succeeded, and a "Test model image" run created after it, on that commit or one of
     the later bot commits, to have succeeded.
  3. Refuses if the latest release was published after the refresh commit (already
     released).
  4. Bumps the latest tag vN.0.0 to v{N+1}.0.0 (per pathogen: they sit at different
     versions) and creates the release on the current HEAD (the commit checked above),
     title = tag, notes generated by GitHub.
A pathogen that fails a check is not released; the others still are. Exit 1 if any failed.

Requires the `gh` CLI authenticated against GitHub.

Usage:
    python scripts/20_cut_releases.py --pathogen abaumannii kpneumoniae calbicans --dry-run
    python scripts/20_cut_releases.py --pathogen abaumannii kpneumoniae calbicans
"""

import argparse
import json
import os
import re
import subprocess
import sys

root = os.path.dirname(os.path.abspath(__file__))
sys.path.append(os.path.join(root, "..", "src"))
from default import ERSILIA_MODEL_IDS, PATHOGENS

_TAG_RE = re.compile(r"^v(\d+)\.0\.0$")
_SKIP_CI = "[skip ci]"
_UPLOAD_WF = "Test and upload model"
_IMAGE_WF = "Test model image"
_BOT_AUTHOR = "ersilia-bot"
_BOT_FILES = {"README.md", "metadata.yml"}


class ReleaseError(Exception):
    pass


def _gh(args: list) -> str:
    res = subprocess.run(["gh", *args], capture_output=True, text=True)
    if res.returncode != 0:
        raise ReleaseError(f"gh {' '.join(args)} failed: {res.stderr.strip()}")
    return res.stdout.strip()


def recent_commits(repo: str) -> list:
    """Newest first: [{sha, message, date}] of the last 30 commits on main."""
    out = _gh(["api", f"repos/{repo}/commits?sha=main&per_page=30"])
    return [{"sha": c["sha"], "message": c["commit"]["message"].split("\n")[0],
             "date": c["commit"]["committer"]["date"]} for c in json.loads(out)]


def refresh_commit(commits: list) -> tuple:
    """(refresh commit, the bot commits after it, newest first)."""
    for i, c in enumerate(commits):
        if _SKIP_CI not in c["message"]:
            return c, commits[:i]
    raise ReleaseError(f"no commit without '{_SKIP_CI}' among the last {len(commits)} on main")


def check_bot_commits(repo: str, bots: list) -> None:
    """Every commit after the refresh must be ersilia-bot's and touch only README.md / metadata.yml."""
    for c in bots:
        detail = json.loads(_gh(["api", f"repos/{repo}/commits/{c['sha']}"]))
        author = detail["commit"]["author"]["name"]
        files = {f["filename"] for f in detail.get("files", [])}
        if author != _BOT_AUTHOR or not files <= _BOT_FILES:
            raise ReleaseError(f"commit {c['sha'][:7]} after the refresh ('{c['message']}') is by {author!r} and changes "
                               f"{sorted(files)}: only {_BOT_AUTHOR} commits on {sorted(_BOT_FILES)} may follow it untested")


def main_runs(repo: str) -> list:
    out = _gh(["run", "list", "--repo", repo, "--branch", "main", "--limit", "50",
               "--json", "workflowName,headSha,status,conclusion,createdAt,url"])
    return json.loads(out)


def latest_release(repo: str) -> tuple:
    """(tag, published_at) of the latest release, or (None, None)."""
    out = _gh(["release", "list", "--repo", repo, "--limit", "1", "--json", "tagName,publishedAt"])
    rel = json.loads(out)
    return (rel[0]["tagName"], rel[0]["publishedAt"]) if rel else (None, None)


def next_tag(current) -> str:
    if current is None:
        return "v1.0.0"
    m = _TAG_RE.match(current)
    if not m:
        raise ReleaseError(f"latest release tag {current!r} doesn't match the expected 'vN.0.0' pattern")
    return f"v{int(m.group(1)) + 1}.0.0"


def check(pathogen: str) -> dict:
    """Everything the release needs, or ReleaseError explaining why not."""
    eos_id = ERSILIA_MODEL_IDS[pathogen]
    repo = f"ersilia-os/{eos_id}"
    commits = recent_commits(repo)
    head = commits[0]
    refresh, bots = refresh_commit(commits)
    print(f"  main HEAD:       {head['sha'][:7]}  {head['message']}")
    print(f"  refresh commit:  {refresh['sha'][:7]}  {refresh['message']}  ({refresh['date']}); "
          f"{len(bots)} '{_SKIP_CI}' commit(s) after it")
    check_bot_commits(repo, bots)
    print(f"  bot commits:     all {len(bots)} by {_BOT_AUTHOR}, only {' / '.join(sorted(_BOT_FILES))}")

    runs = main_runs(repo)
    upload = next((r for r in runs if r["workflowName"] == _UPLOAD_WF), None)
    if upload is None:
        raise ReleaseError(f"no '{_UPLOAD_WF}' run on main")
    print(f"  {_UPLOAD_WF}: {upload['headSha'][:7]}  {upload['status']}/{upload['conclusion']}  {upload['url']}")
    if upload["headSha"] != refresh["sha"]:
        raise ReleaseError(f"the newest '{_UPLOAD_WF}' run is on {upload['headSha'][:7]}, not on the refresh commit "
                           f"{refresh['sha'][:7]}: CI for the refresh has not run yet")
    if upload["status"] != "completed" or upload["conclusion"] != "success":
        raise ReleaseError(f"'{_UPLOAD_WF}' is {upload['status']}/{upload['conclusion']}, not completed/success")

    allowed = {refresh["sha"]} | {c["sha"] for c in bots}
    image = next((r for r in runs if r["workflowName"] == _IMAGE_WF and r["createdAt"] >= upload["createdAt"]
                  and r["headSha"] in allowed), None)
    if image is None:
        raise ReleaseError(f"no '{_IMAGE_WF}' run after the upload run on the refresh commit or its bot commits")
    print(f"  {_IMAGE_WF}:     {image['headSha'][:7]}  {image['status']}/{image['conclusion']}  {image['url']}")
    if image["status"] != "completed" or image["conclusion"] != "success":
        raise ReleaseError(f"'{_IMAGE_WF}' is {image['status']}/{image['conclusion']}, not completed/success")

    current, published = latest_release(repo)
    if published is not None and published >= refresh["date"]:
        raise ReleaseError(f"{current} was published at {published}, after the refresh commit: already released")
    new_tag = next_tag(current)
    print(f"  release:         {current or '(none)'} -> {new_tag}  (on {head['sha'][:7]})")
    return {"repo": repo, "tag": new_tag, "target": head["sha"]}


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Cut the next GitHub release of pathogens' Hub repos, only if the post-push CI of the refresh succeeded.")
    parser.add_argument("--pathogen", required=True, nargs="+", choices=PATHOGENS, metavar="PATHOGEN")
    parser.add_argument("--dry-run", action="store_true", help="run every check and print the release, create nothing")
    args = parser.parse_args()

    failed = []
    for pathogen in args.pathogen:
        print(f"[{pathogen}] ({ERSILIA_MODEL_IDS[pathogen]})")
        try:
            plan = check(pathogen)
            if args.dry_run:
                print(f"  DRY RUN: would create {plan['tag']}")
                continue
            _gh(["release", "create", plan["tag"], "--repo", plan["repo"], "--target", plan["target"],
                 "--title", plan["tag"], "--generate-notes"])
            url = _gh(["release", "view", plan["tag"], "--repo", plan["repo"], "--json", "url", "--jq", ".url"])
            print(f"  RELEASED {plan['tag']}: {url}")
        except ReleaseError as e:
            print(f"  NOT RELEASED: {e}")
            failed.append(pathogen)

    if failed:
        sys.exit(f"FAIL: not released: {', '.join(failed)}")


if __name__ == "__main__":
    main()
